Market/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Market import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Store.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Store/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from Store import views
from Store.views import HomeView, ProductView, CartView, CheckoutView, TransactionView, RemoveOrderView, StoreView, \
    LoginView, RegisterView, ForgotPasswordView, ChangePasswordView

app_name = "Store"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("login", LoginView.as_view(), name="login"),
    path("register", RegisterView.as_view(), name="register"),
    path("logout", views.log_out, name="logout"),
    path("forgot_password", ForgotPasswordView.as_view(), name="forgot_password"),
    path("forgot_password/<int:id>/change_password", ChangePasswordView.as_view(), name="change_password"),
    path("store/<int:id>", StoreView.as_view(), name="store"),
    path("store/product/<int:id>", ProductView.as_view(), name="product"),
    path("cart", CartView.as_view(), name="cart"),
    path("cart/<int:id>/remove_order", RemoveOrderView.as_view(), name="remove_order"),
    path("cart/checkout", CheckoutView.as_view(), name="checkout"),
    path("transactions", TransactionView.as_view(), name="transactions"),
]

Store/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Customer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=250)
    username = models.CharField(max_length=25)
    email = models.EmailField()

    def __str__(self):
        return self.full_name


class Category(models.Model):
    name = models.CharField(max_length=250)
    image = models.FileField(upload_to="category")
    description = models.CharField(max_length=1000)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    image = models.FileField(upload_to="product")
    description = models.CharField(max_length=1000)

    def __str__(self):
        return self.name


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    amount = models.DecimalField(decimal_places=2, max_digits=10)

    def __str__(self):
        return self.product.name


class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    orders = models.ManyToManyField(Order)
    total_amount = models.DecimalField(decimal_places=2, max_digits=10, default=0)
    order_placed = models.BooleanField(default=False)

    def calculate_total_cost(self):
        self.total_amount = sum([
            order.amount for order in self.orders.all()
        ])

    def __str__(self):
        return self.customer.full_name


class Transaction(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=16)
    address = models.CharField(max_length=1000)
    is_success = models.BooleanField(default=False)
    date = models.DateTimeField(default=datetime.datetime.now())

    def __str__(self):
        return self.transaction_id

Store/views.py
import string
import random

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View

from Store.models import Product, Customer, Cart, Order, Transaction, Category

random = random.Random()


# Create your views here.
class LoginView(View):
    template_name = "store/login.html"

    def get(self, request):
        # Go to the register page
        return render(request, self.template_name)

    def post(self, request):
        # Check if form is submitting
        if request.method == "POST":
            # Collect inputs
            username = request.POST.get("username").strip()
            password = request.POST.get("password")

            # Authenticate user
            user = authenticate(username=username, password=password)

            # Check if user exist
            if user is not None:
                # Login user
                login(request, user)
                # Redirect to learning page
                return HttpResponseRedirect(reverse("Store:home"))
            else:
                # Send error message
                messages.error(request, "Invalid credentials")
                # Redirect to login page
                return HttpResponseRedirect(reverse("Store:login"))


class RegisterView(View):

    def post(self, request):
        # Check if form is submitting
        if request.method == "POST":
            # Collect inputs
            full_name = request.POST.get("full_name").strip().upper()
            username = request.POST.get("username").strip()
            email = request.POST.get("email").strip()
            password = request.POST.get("password")
            confirm_password = request.POST.get("confirm_password").strip()

            # Check if user with username already exists
            if not User.objects.filter(username=username).exists():
                if password == confirm_password:
                    # Create user and person
                    user = User.objects.create_user(username=username, password=password)
                    customer = Customer.objects.create(user=user, full_name=full_name, username=username, email=email)
                    Cart.objects.create(customer=customer)
                    # Send success message
                    messages.success(request, "Registration successful. Please login")
                    # Redirect to login page
                    return HttpResponseRedirect(reverse("Store:login"))
                else:
                    # Send error message
                    messages.error(request, "Password does not match")
                    # Redirect back to register page
                    return HttpResponseRedirect(reverse("Store:login"))
            else:
                # Send error message
                messages.error(request, "Username already exists")
                # Redirect back to register page
                return HttpResponseRedirect(reverse("Store:login"))


class ForgotPasswordView(View):
    template_name = "store/forgot_password.html"

    def get(self, request):
        # Go to the register page
        return render(request, self.template_name)

    def post(self, request):
        # Collect inputs
        username = request.POST.get("username").strip()

        if User.objects.filter(username=username).exists():
            user = User.objects.get(username=username)
            customer = Customer.objects.get(user=user)
            return HttpResponseRedirect(reverse("Store:change_password", args=(customer.id,)))
        else:
            messages.error(request, "User does not exist")
            return HttpResponseRedirect(reverse("Store:forgot_password"))


class ChangePasswordView(View):
    template_name = "store/change_password.html"

    def get(self, request, id):
        # Go to the register page
        return render(request, self.template_name)

    def post(self, request, id):
        customer = Customer.objects.get(id=id)

        # Collect inputs
        password = request.POST.get("password").strip()
        confirm_password = request.POST.get("confirm_password").strip()

        if password == confirm_password:
            customer.user.set_password(password)
            customer.user.save()
            messages.success(request, "Password update successful")
            return HttpResponseRedirect(reverse("Store:login"))
        else:
            messages.error(request, "Password does not match")
            return HttpResponseRedirect(reverse("Store:change_password", args=(customer.id,)))


class HomeView(View):
    template_name = "store/home.html"

    def get(self, request):
        all_categories = Category.objects.all()
        context = {"all_categories": all_categories}

        if request.user.is_authenticated and not request.user.is_superuser:
            customer = Customer.objects.get(user=request.user)
            context = {"customer": customer, "all_categories": all_categories}

        return render(request, self.template_name, context=context)


class StoreView(View):
    template_name = "store/store.html"

    def get(self, request, id):
        category = Category.objects.get(id=id)
        products = Product.objects.filter(category=category)
        context = {"products": products}

        if request.user.is_authenticated and not request.user.is_superuser:
            customer = Customer.objects.get(user=request.user)
            context = {"customer": customer, "category": category, "products": products}

        return render(request, self.template_name, context=context)


class ProductView(View):
    template_name = "store/product.html"

    def get(self, request, id):
        product = Product.objects.get(id=id)
        context = {"product": product}

        if request.user.is_authenticated and not request.user.is_superuser:
            customer = Customer.objects.get(user=request.user)
            context = {"customer": customer, "product": product}

        return render(request, self.template_name, context=context)

    @method_decorator(login_required())
    def post(self, request, id):
        quantity = request.POST.get("quantity")

        customer = Customer.objects.get(user=request.user)
        product = Product.objects.get(id=id)
        try:
            cart = Cart.objects.get(customer=customer, order_placed=False)
        except Exception:
            cart = Cart.objects.create(customer=customer)
        amount = float(product.price) * float(quantity)

        if int(quantity) > 0:
            order = Order.objects.create(customer=customer, product=product, quantity=quantity, amount=amount)
            cart.orders.add(order)
            cart.calculate_total_cost()
            cart.save()
            messages.success(request, "Order added to cart")
            return HttpResponseRedirect(reverse("Store:cart"))
        else:
            messages.error(request, "Enter valid quantity")
            return HttpResponseRedirect(reverse("Store:product", args=(product.id,)))


class CartView(View):
    template_name = "store/cart.html"

    @method_decorator(login_required())
    def get(self, request):
        customer = Customer.objects.get(user=request.user)

        try:
            cart = Cart.objects.get(customer=customer, order_placed=False)
        except Exception:
            cart = Cart.objects.create(customer=customer)

        products = []
        total_sum = 0
        try:
            for order in cart.orders.all():
                product = {
                        "id": order.id,
                        "name": order.product.name,
                        "quantity": order.quantity,
                        "amount": order.amount,
                        "price": order.product.price,
                        "image": order.product.image,
                        "description": order.product.description,
                    }
                total_sum += order.amount
                products.append(product)
        except Exception:
            pass
        context = {"customer": customer, "products": products, "total_sum": total_sum}

        return render(request, self.template_name, context=context)


class RemoveOrderView(View):

    @method_decorator(login_required())
    def get(self, request, id):
        order = Order.objects.get(id=id)
        customer = Customer.objects.get(user=request.user)
        cart = Cart.objects.get(customer=customer)
        cart.orders.remove(order)
        cart.save()
        messages.success(request, "Order removed from cart")
        return HttpResponseRedirect(reverse("Store:cart"))


class CheckoutView(View):
    template_name = "store/checkout.html"

    @method_decorator(login_required())
    def get(self, request):
        customer = Customer.objects.get(user=request.user)
        cart = Cart.objects.get(customer=customer, order_placed=False)
        products = [
            {
                "id": order.id,
                "name": order.product.name,
                "quantity": order.quantity,
                "amount": order.amount,
                "price": order.product.price,
                "image": order.product.image,
            } for order in cart.orders.all()
        ]
        total_sum = sum([
            order.amount for order in cart.orders.all()
        ])
        context = {"customer": customer, "products": products, "total_sum": total_sum}

        return render(request, self.template_name, context=context)

    @method_decorator(login_required())
    def post(self, request):
        address = request.POST.get("address")

        customer = Customer.objects.get(user=request.user)

Store/templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>

    {% for msg in messages %}
        <div class="container">
            <h5>{{ msg }}</h5>
        </div>
        {% endfor %}

    <section class="cart-items">
        {% for product in products %}
        <div class="cart-item">
            <img src="/media/{{ product.image }}" alt="{{ product.name }}" style="width:200px">
            <div class="item-details">
                <h2>{{ product.name }}</h2>
                <p>Description: {{ product.description }}</p>
                <p>Price: ${{ product.price }}</p>
                <p>Quantity: {{ product.quantity }}</p>
                <p>Amount: ${{ product.amount }}</p>
                <a href="{% url 'Store:remove_order' product.id %}"><button class="remove-item">Remove</button></a>
            </div>
        </div>
        {% empty %}
        <div class="cart-item">
            <h4>No item has been added to cart</h4>
        </div>
        {% endfor %}
    </section>

    <section class="cart-summary">
        <h2>Cart Summary</h2>
        <div class="summary-details">
            <p>Total: ${{ total_sum }}</p>
        </div>
        <a href="{% url 'Store:checkout' %}"><button class="checkout-button">Checkout</button></a>
    </section>
</main>
{% endblock content %}

Store/templates/store/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>
    <section class="container">
        <div class="login-form">
            <h2>Change Password</h2>
            {% for msg in messages %}
            <div class="container">
                <h5>{{ msg }}</h5>
            </div>
            {% endfor %}
            <form action="" method="post" id="login-form" class="active">
                {% csrf_token %}
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
                <label for="confirm_password">Confirm Password:</label>
                <input type="password" id="confirm_password" name="confirm_password" required>
                <button type="submit" class="login-button">Login</button>
            </form>
        </div>
    </section>
</main>
{% endblock content %}

Store/templates/store/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>

    {% for msg in messages %}
        <div class="container">
            <h5>{{ msg }}</h5>
        </div>
        {% endfor %}

    <section class="checkout-items">
        {% for product in products %}
        <div class="checkout-item">
            <img src="/media/{{ product.image }}" alt="{{ product.name }}" style="width:200px">
            <div class="item-details">
                <h2>{{ product.name }}</h2>
                <p>Price: ${{ product.price }}</p>
                <p>Quantity: {{ product.quantity }}</p>
                <p>Amount: ${{ product.amount }}</p>
            </div>
        </div>
        {% endfor %}
    </section>

    <section class="checkout-summary">
        <h2>Order Summary</h2>
        <div class="summary-details">
            <div class="summary-details">
                <p>Total: ${{ total_sum }}</p>
            </div>
        </div>
        <form action="" method="post" class="checkout-form">
            {% csrf_token %}
            <h3>Delivery Information</h3>
            <label for="address">Address:</label>
            <textarea id="address" name="address" required></textarea>
            <button type="submit" class="checkout-button">Place Order</button>
        </form>
    </section>
</main>
{% endblock content %}

Store/templates/store/forgot_password.html
{% extends 'auth.html' %}
{% load static %}

{% block content %}
<main>
    <section class="container">
        <div class="login-form">
            <h2>Forgot Password</h2>
            {% for msg in messages %}
            <div class="container">
                <h5>{{ msg }}</h5>
            </div>
            {% endfor %}
            <form action="" method="post" id="login-form" class="active">
                {% csrf_token %}
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
                <button type="submit" class="login-button">Submit</button>
            </form>
        </div>
    </section>
</main>
{% endblock content %}

Store/templates/store/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% for msg in messages %}
        <div class="container">
            <h5>{{ msg }}</h5>
        </div>
        {% endfor %}

<section style="text-align: center; margin: 30px">
    <div>
        <h2>Welcome to Angel Aesthetics</h2>
        <p style="margin: 10px"><i>"Your one-stop destination for beauty and wellness products."</i></p>
    </div>
</section>

<section class="featured-products">
    <h2>Featured Product Categories</h2>
    <div class="product-grid">
        {% for category in all_categories %}
        <div class="product-item">
            <img src="{{ category.image.url }}" alt="Product 1">
            <h3>{{ category.name }}</h3>
            <p style="margin: 10px">{{ category.description }}</p>
            <a href="{% url 'Store:store' category.id %}" class="cta-button">View Products</a>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock content %}

Store/templates/store/login.html
{% extends 'auth.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container">
      <div class="login-register">
        <form action="" method="post" id="login-form" class="active">
          {% csrf_token %}
          <h2>Login</h2>
          {% for msg in messages %}
          <div class="container">
              <h5>{{ msg }}</h5>
          </div>
          {% endfor %}
          <label for="username">Username:</label>
          <input type="text" id="username" name="username" required>
          <label for="password">Password:</label>
          <input type="password" id="password" name="password" required>
          <button type="submit">Login</button>
          <p><a href="{% url 'Store:forgot_password' %}">Forgot Password?</a></p>
          <p class="toggle">Don't have an account? <a href="#" id="register-link">Register</a></p>
        </form>

        <form action="{% url 'Store:register' %}" method="post" id="register-form">
          {% csrf_token %}
          <h2>Register</h2>
          <label for="name">Full Name:</label>
          <input type="text" id="name" name="full_name" required>
          <label for="username2">Username:</label>
          <input type="text" id="username2" name="username" required>
          <label for="email">Email:</label>
          <input type="email" id="email" name="email" required>
          <label for="password2">Password:</label>
          <input type="password" id="password2" name="password" required>
          <label for="confirm_password">Confirm Password:</label>
          <input type="password" id="confirm_password" name="confirm_password" required>
          <button type="submit">Register</button>
          <p class="toggle">Already have an account? <a href="#" id="login-link">Login</a></p>
        </form>
      </div>
    </div>
  </main>
{% endblock content %}

Store/templates/store/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>

    {% for msg in messages %}
        <div class="container">
            <h5>{{ msg }}</h5>
        </div>
        {% endfor %}

    <section class="store">
        <div class="store-info">
            <h2>{{ product.name }}</h2>
            <p>Category: {{ product.category.name }}</p>
            <p>Description: {{ product.description }}</p>
            <p>Price: {{ product.price }}</p>
            <div>
                <form action="" method="post">
                    {% csrf_token %}
                    <label for="quantity">Quantity</label>
                    <input type="number" name="quantity" id="quantity"><br>
                    <button style="margin:10px" type="submit" class="add-to-cart">Add to Cart</button>
                </form>
            </div>
        </div>

        <div class="store-image">
            <img src="/media/{{ product.image }}" alt="{{ product.name }}">
        </div>
    </section>
</main>
{% endblock content %}

Store/templates/store/store.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>

    {% for msg in messages %}
        <div class="container">
            <h5>{{ msg }}</h5>
        </div>
        {% endfor %}

    <h2>{{ category.name }}</h2>
    <section class="store">
        <div class="store-items">
            {% for product in products %}
            <div class="store-item">
                <img src="/media/{{ product.image }}" alt="{{ product.name }}">
                <h3>{{ product.name }}</h3>
                <p>Price: ${{ product.price }}</p>
                <a href="{% url 'Store:product' product.id %}"><button class="add-to-cart">View Product</button></a>
            </div>
            {% empty %}
            <div class="cart-item">
                <h4>Products are currently unavailable</h4>
            </div>
            {% endfor %}
        </div>
    </section>
</main>
{% endblock content %}

Store/templates/store/transaction.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>

    {% for msg in messages %}
        <div class="container">
            <h5>{{ msg }}</h5>
        </div>
        {% endfor %}

    <h2 style="margin:20px">Transactions</h2>
    <section class="cart-items">
        <div class="product-grid">
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Product</th>
                        <th>Amount</th>
                        <th>Trans. Id</th>
                        <th>Date</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for trans in transactions %}
                    <tr>
                        <td>{{ trans.customer.username }}</td>
                        <td>
                            {% for order in trans.cart.orders.all %}
                            {{ order.product.name }}<br>
                            {% endfor %}
                        </td>
                        <td>$ {{ trans.cart.total_amount }}</td>
                        <td>{{ trans.transaction_id }}</td>
                        <td>{{ trans.date }}</td>
                        <td>
                            {% if trans.is_success %}
                            <b style="color: rgb(19, 116, 19);">Success</b>
                            {% else %}
                            <b style="color: rgb(236, 201, 0);">Pending</b>
                            {% endif %}
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="6">No transactions made yet</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>

</main>
{% endblock content %}