Market/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Market import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Store.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Store/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from Store import views
from Store.views import HomeView, ProductView, CartView, CheckoutView, TransactionView, RemoveOrderView, StoreView, \
    LoginView, RegisterView, ForgotPasswordView, ChangePasswordView

app_name = "Store"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("login", LoginView.as_view(), name="login"),
    path("register", RegisterView.as_view(), name="register"),
    path("logout", views.log_out, name="logout"),
    path("forgot_password", ForgotPasswordView.as_view(), name="forgot_password"),
    path("forgot_password/<int:id>/change_password", ChangePasswordView.as_view(), name="change_password"),
    path("store/<int:id>", StoreView.as_view(), name="store"),
    path("store/product/<int:id>", ProductView.as_view(), name="product"),
    path("cart", CartView.as_view(), name="cart"),
    path("cart/<int:id>/remove_order", RemoveOrderView.as_view(), name="remove_order"),
    path("cart/checkout", CheckoutView.as_view(), name="checkout"),
    path("transactions", TransactionView.as_view(), name="transactions"),
]

templates/auth.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Online Marketplace</title>
  <link rel="stylesheet" href="{% static 'store/login.css' %}">
</head>
<body>
  <header>
    <div class="logo">
      <!-- Place your logo here -->
      <img src="{% static 'images/logo.png' %}" width="70px" alt="Angel Aesthetics Logo">
    </div>
    <h1>Online Marketplace</h1>
  </header>

  <nav>
    <ul>
      <li><a href="{% url 'Store:home' %}">Home</a></li>
      <li><a href="{% url 'Store:cart' %}">Cart</a></li>
      <li><a href="{% url 'Store:transactions' %}">Transactions</a></li>
      {% if customer %}
      <li><a href="{% url 'Store:logout' %}">Logout</a></li>
      {% else %}
      <li><a href="{% url 'Store:login' %}">Sign up/Log-in</a></li>
      {% endif %}
    </ul>
  </nav>

  {% block content %}
  {% endblock content %}


  <footer>
    <p>&copy; 2023 Online Marketplace. All rights reserved.</p>
  </footer>

  <script src="{% static 'store/login.js' %}"></script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Online Marketplace</title>
  <link rel="stylesheet" href="{% static 'store/style.css' %}">
</head>
<body>
  <header>
    <div class="logo">
      <!-- Place your logo here -->
      <img src="{% static 'images/logo.png' %}" width="70px" alt="Logo">
    </div>
    <h1>Online Marketplace</h1>
  </header>

  <nav>
    <ul>
      <li><a href="{% url 'Store:home' %}">Home</a></li>
      <li><a href="{% url 'Store:cart' %}">Cart</a></li>
      <li><a href="{% url 'Store:transactions' %}">Transactions</a></li>
      {% if customer %}
      <li><a href="{% url 'Store:logout' %}">Logout</a></li>
      {% else %}
      <li><a href="{% url 'Store:login' %}">Sign up/Log-in</a></li>
      {% endif %}
    </ul>
  </nav>

  {% block content %}
  {% endblock content %}


  <footer>
    <p>&copy; 2023 Online Marketplace. All rights reserved.</p>
  </footer>

  <script src="{% static 'store/main.js' %}"></script>
</body>
</html>